//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entegref.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=185.184.26.245;Database=39391097764; User Id=fatih; Password=05101981;")]
        public string connectionstring {
            get {
                return ((string)(this["connectionstring"]));
            }
            set {
                this["connectionstring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=185.184.26.245;Database=Netbil_Connector; User ID=fatih;Password=05101981;" +
            "")]
        public string connectionstring2 {
            get {
                return ((string)(this["connectionstring2"]));
            }
            set {
                this["connectionstring2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("387607")]
        public string TrendyolId {
            get {
                return ((string)(this["TrendyolId"]));
            }
            set {
                this["TrendyolId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GOD4ohApME0Y1r5YBnmv")]
        public string TrendyolApi {
            get {
                return ((string)(this["TrendyolApi"]));
            }
            set {
                this["TrendyolApi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lx6cAnNSJQjKBUaZ3Q9W")]
        public string TrendyolSecretkey {
            get {
                return ((string)(this["TrendyolSecretkey"]));
            }
            set {
                this["TrendyolSecretkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=185.184.26.245;Database=Netbil_Connector; User ID=fatih;Password=05101981;" +
            "")]
        public string CloudServerNetbil {
            get {
                return ((string)(this["CloudServerNetbil"]));
            }
            set {
                this["CloudServerNetbil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=185.184.26.245;Database={1}; User ID=fatih;Password=05101981;")]
        public string CoudServerLocal {
            get {
                return ((string)(this["CoudServerLocal"]));
            }
            set {
                this["CoudServerLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Remember {
            get {
                return ((bool)(this["Remember"]));
            }
            set {
                this["Remember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VKN {
            get {
                return ((string)(this["VKN"]));
            }
            set {
                this["VKN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecretPhase {
            get {
                return ((string)(this["SecretPhase"]));
            }
            set {
                this["SecretPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XTsrN5elDpbvRhnjacYmRoFRG5FFBsu4IYPacw8u")]
        public string CicekSepetiApi_key {
            get {
                return ((string)(this["CicekSepetiApi_key"]));
            }
            set {
                this["CicekSepetiApi_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("park-entegrasyon")]
        public string ParkKullaniciAdi {
            get {
                return ((string)(this["ParkKullaniciAdi"]));
            }
            set {
                this["ParkKullaniciAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cmc2017*!Park")]
        public string ParkParola {
            get {
                return ((string)(this["ParkParola"]));
            }
            set {
                this["ParkParola"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TicimaxAlanAdi {
            get {
                return ((string)(this["TicimaxAlanAdi"]));
            }
            set {
                this["TicimaxAlanAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TicimaxYetkiKodu {
            get {
                return ((string)(this["TicimaxYetkiKodu"]));
            }
            set {
                this["TicimaxYetkiKodu"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wstest.parkentegrasyon.com.tr/EIrsaliyeService.asmx")]
        public string Entegref_tr_com_parkentegrasyon_Irsaliye_test_EIrsaliyeService {
            get {
                return ((string)(this["Entegref_tr_com_parkentegrasyon_Irsaliye_test_EIrsaliyeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wstest.parkentegrasyon.com.tr/EFaturaService.asmx")]
        public string Entegref_tr_com_parkentegrasyon_EFatura_test_EFaturaService {
            get {
                return ((string)(this["Entegref_tr_com_parkentegrasyon_EFatura_test_EFaturaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws.parkentegrasyon.com.tr/EFaturaIntegration.asmx")]
        public string Entegref_tr_com_parkentegrasyon_Goruntu_EFaturaIntegration {
            get {
                return ((string)(this["Entegref_tr_com_parkentegrasyon_Goruntu_EFaturaIntegration"]));
            }
        }
    }
}
